#!/usr/bin/env bash

INSTALL_MOUNTPOINT="/mnt"
REPO_INSTALL_DIR="/opt/virginator"
CONFIG_INSTALL_DIR="$REPO_INSTALL_DIR/config"
GENERATED_PARTITION_CONFIG="$VIRGINATOR_ROOT/config/generated-partitions.sh"

BOOT_PARTITION="PARTLABEL=EFI"
ROOT_PARTITION="PARTLABEL=ROOT"
HOME_PARTITION="PARTLABEL=HOME"
VAULT_ENABLED="yes"
VAULT_PARTITION="PARTLABEL=VAULT"

BOOT_FS_LABEL="EFI"
ROOT_FS_LABEL="arch-root"

BOOT_FS_TYPE="vfat"
ROOT_FS_TYPE="ext4"
HOME_FS_TYPE="ext4"

BOOT_MOUNT_SUBDIR="boot"
ROOT_MOUNT_OPTIONS="defaults"
HOME_MOUNT_OPTIONS="defaults"

PRIMARY_USER_SHELL="/usr/bin/fish"
PRIMARY_USER_GROUPS=(wheel)

VAULT_MAPPER_NAME="vault"
VAULT_MOUNTPOINT="/vault"

GO_VERSION=""
NODE_VERSION=""
NODE_DISTRO_ARCH="linux-x64"
NEOVIM_NIGHTLY_URL=""
BITWARDEN_CLI_VERSION="latest"
AUR_HELPER_PACKAGE="paru-bin"
AUR_PACKAGES=(
  brave-bin
)

CPU_MICROCODE_PACKAGE=""
CPU_MICROCODE_IMAGE=""

LOADER_TIMEOUT="2"
