#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
OUTPUT_FILE=${OUTPUT_FILE:-$REPO_ROOT/config/generated-partitions.sh}

usage() {
  cat <<'EOF'
Usage:
  ./scripts/select-partitions.sh

Interactively select boot, root, home, and optional vault partitions with skim.
The selected PARTUUID values are written to config/generated-partitions.sh by default.
EOF
}

require_command() {
  local command_name
  for command_name in "$@"; do
    command -v "$command_name" >/dev/null 2>&1 || {
      printf 'missing required command: %s\n' "$command_name" >&2
      exit 1
    }
  done
}

load_candidates() {
  local line path size fstype partlabel label partuuid mountpoints renamed_line

  while IFS= read -r line; do
    renamed_line=${line//PATH=/LSBLK_PATH=}
    renamed_line=${renamed_line//SIZE=/LSBLK_SIZE=}
    renamed_line=${renamed_line//FSTYPE=/LSBLK_FSTYPE=}
    renamed_line=${renamed_line//PARTLABEL=/LSBLK_PARTLABEL=}
    renamed_line=${renamed_line//LABEL=/LSBLK_LABEL=}
    renamed_line=${renamed_line//PARTUUID=/LSBLK_PARTUUID=}
    renamed_line=${renamed_line//MOUNTPOINTS=/LSBLK_MOUNTPOINTS=}

    unset LSBLK_PATH LSBLK_SIZE LSBLK_FSTYPE LSBLK_PARTLABEL LSBLK_LABEL LSBLK_PARTUUID LSBLK_MOUNTPOINTS
    eval "$renamed_line"

    path=${LSBLK_PATH:-}
    size=${LSBLK_SIZE:-}
    fstype=${LSBLK_FSTYPE:-}
    partlabel=${LSBLK_PARTLABEL:-}
    label=${LSBLK_LABEL:-}
    partuuid=${LSBLK_PARTUUID:-}
    mountpoints=${LSBLK_MOUNTPOINTS:-}

    [[ -n "$path" && -n "$partuuid" ]] || continue
    CANDIDATE_PATHS+=("$path")
    CANDIDATE_LINES[$path]=$(printf '%-18s | %-8s | %-11s | %-10s | %-12s | %-36s | %s' \
      "$path" "${size:--}" "${fstype:--}" "${partlabel:--}" "${label:--}" "$partuuid" "${mountpoints:--}")
    CANDIDATE_TYPES[$path]=$fstype
    CANDIDATE_PARTUUIDS[$path]=$partuuid
  done < <(lsblk -P -o PATH,SIZE,FSTYPE,PARTLABEL,LABEL,PARTUUID,MOUNTPOINTS)
}

build_menu() {
  local preferred_regex excluded_path path line
  preferred_regex=$1
  excluded_path=${2:-}

  for path in "${CANDIDATE_PATHS[@]}"; do
    [[ -n "$excluded_path" && "$path" == "$excluded_path" ]] && continue
    line=${CANDIDATE_LINES[$path]}
    if [[ -n "$preferred_regex" && ${CANDIDATE_TYPES[$path]:-} =~ $preferred_regex ]]; then
      printf '* %s\n' "$line"
    else
      printf '  %s\n' "$line"
    fi
  done
}

pick_partition() {
  local header preferred_regex forbidden_csv selection selected_path trimmed
  header=$1
  preferred_regex=$2
  forbidden_csv=${3:-}

  selection=$(build_menu "$preferred_regex" | sk --ansi --height 60% --prompt "$header > " --header 'path | size | fstype | partlabel | label | partuuid | mountpoints' --nth 1,3,4,5,6,7) || exit 1
  trimmed=${selection#??}
  selected_path=${trimmed%% |*}
  selected_path=${selected_path#"${selected_path%%[![:space:]]*}"}
  selected_path=${selected_path%"${selected_path##*[![:space:]]}"}

  if [[ -n "$forbidden_csv" && ",$forbidden_csv," == *",$selected_path,"* ]]; then
    printf 'selection %s was already used\n' "$selected_path" >&2
    exit 1
  fi

  printf '%s\n' "$selected_path"
}

confirm() {
  local answer
  printf 'Write %s? [y/N] ' "$OUTPUT_FILE" >&2
  read -r answer
  [[ "$answer" =~ ^[Yy]([Ee][Ss])?$ ]]
}

main() {
  local boot_path root_path home_path vault_path answer used_paths
  declare -ga CANDIDATE_PATHS=()
  declare -gA CANDIDATE_LINES=()
  declare -gA CANDIDATE_TYPES=()
  declare -gA CANDIDATE_PARTUUIDS=()

  if [[ ${1:-} == "--help" ]]; then
    usage
    exit 0
  fi

  require_command lsblk sk
  load_candidates
  ((${#CANDIDATE_PATHS[@]} > 0)) || {
    printf 'no partitions with PARTUUIDs were found\n' >&2
    exit 1
  }

  boot_path=$(pick_partition 'Select boot partition' '^vfat$')
  used_paths=$boot_path
  root_path=$(pick_partition 'Select root partition' '^ext4$' "$used_paths")
  used_paths="$used_paths,$root_path"
  home_path=$(pick_partition 'Select home partition' '^ext4$' "$used_paths")
  used_paths="$used_paths,$home_path"

  printf 'Add a vault partition? [y/N] ' >&2
  read -r answer
  if [[ "$answer" =~ ^[Yy]([Ee][Ss])?$ ]]; then
    vault_path=$(pick_partition 'Select vault partition' '^crypto_LUKS$' "$used_paths")
  else
    vault_path=''
  fi

  printf '\nGenerated selection:\n'
  printf '  boot : %s\n' "$boot_path"
  printf '  root : %s\n' "$root_path"
  printf '  home : %s\n' "$home_path"
  if [[ -n "$vault_path" ]]; then
    printf '  vault: %s\n' "$vault_path"
  else
    printf '  vault: disabled\n'
  fi

  mkdir -p "$(dirname -- "$OUTPUT_FILE")"

  if ! confirm; then
    printf 'aborted\n' >&2
    exit 1
  fi

  {
    printf '# generated by scripts/select-partitions.sh\n'
    printf 'BOOT_PARTITION="PARTUUID=%s"\n' "${CANDIDATE_PARTUUIDS[$boot_path]}"
    printf 'ROOT_PARTITION="PARTUUID=%s"\n' "${CANDIDATE_PARTUUIDS[$root_path]}"
    printf 'HOME_PARTITION="PARTUUID=%s"\n' "${CANDIDATE_PARTUUIDS[$home_path]}"
    if [[ -n "$vault_path" ]]; then
      printf 'VAULT_ENABLED="yes"\n'
      printf 'VAULT_PARTITION="PARTUUID=%s"\n' "${CANDIDATE_PARTUUIDS[$vault_path]}"
    else
      printf 'VAULT_ENABLED="no"\n'
      printf 'VAULT_PARTITION=""\n'
    fi
  } > "$OUTPUT_FILE"

  printf 'wrote %s\n' "$OUTPUT_FILE"
}

main "$@"
